// Comprehensive mock data for the dashboard
import type { User, Course, Student, Instructor, Lesson, Transaction, AnalyticsData } from "./types"

export const mockUser: User = {
  id: "admin-001",
  email: "admin@eduhub.com",
  name: "Sarah Anderson",
  role: "admin",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
  department: "Administration",
  joinDate: "2023-01-15",
}

export const mockCourses: Course[] = [
  {
    id: "course-001",
    title: "React Advanced Patterns",
    description: "Master advanced React patterns and hooks",
    category: "Web Development",
    instructor: "John Smith",
    instructorId: "inst-001",
    status: "Published",
    enrollments: 2340,
    rating: 4.8,
    thumbnail: "https://images.unsplash.com/photo-1633356713697-a8be5450a126?w=400",
    createdAt: "2024-01-10",
    updatedAt: "2024-12-15",
    price: 99.99,
    lessonCount: 48,
  },
  {
    id: "course-002",
    title: "Data Science Fundamentals",
    description: "Learn data science from scratch",
    category: "Data Science",
    instructor: "Emily Johnson",
    instructorId: "inst-002",
    status: "Published",
    enrollments: 1890,
    rating: 4.7,
    thumbnail: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    createdAt: "2024-02-20",
    updatedAt: "2024-12-10",
    price: 129.99,
    lessonCount: 52,
  },
  {
    id: "course-003",
    title: "Business Strategy 101",
    description: "Essential business strategies for growth",
    category: "Business",
    instructor: "Michael Chen",
    instructorId: "inst-003",
    status: "Published",
    enrollments: 1245,
    rating: 4.6,
    thumbnail: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    createdAt: "2024-03-05",
    updatedAt: "2024-12-08",
    price: 79.99,
    lessonCount: 36,
  },
  {
    id: "course-004",
    title: "UI/UX Design Masterclass",
    description: "Create beautiful user interfaces",
    category: "Design",
    instructor: "Lisa Wong",
    instructorId: "inst-004",
    status: "Published",
    enrollments: 1567,
    rating: 4.9,
    thumbnail: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400",
    createdAt: "2024-04-12",
    updatedAt: "2024-12-12",
    price: 109.99,
    lessonCount: 44,
  },
  {
    id: "course-005",
    title: "Flutter Mobile Development",
    description: "Build cross-platform mobile apps",
    category: "Mobile",
    instructor: "David Kumar",
    instructorId: "inst-005",
    status: "Draft",
    enrollments: 340,
    rating: 4.5,
    thumbnail: "https://images.unsplash.com/photo-1512941691920-25bda36dc643?w=400",
    createdAt: "2024-05-01",
    updatedAt: "2024-12-14",
    price: 119.99,
    lessonCount: 50,
  },
]

export const mockStudents: Student[] = [
  {
    id: "student-001",
    name: "Alex Morgan",
    email: "alex@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    enrolledCourses: 5,
    completionRate: 85,
    status: "Active",
    joinDate: "2024-01-10",
    totalHours: 245,
    averageRating: 4.6,
    lastActive: "2024-12-15 14:30",
  },
  {
    id: "student-002",
    name: "Jordan Lee",
    email: "jordan@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan",
    enrolledCourses: 3,
    completionRate: 72,
    status: "Active",
    joinDate: "2024-02-15",
    totalHours: 156,
    averageRating: 4.3,
    lastActive: "2024-12-15 11:20",
  },
  {
    id: "student-003",
    name: "Casey Rivera",
    email: "casey@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Casey",
    enrolledCourses: 7,
    completionRate: 92,
    status: "Active",
    joinDate: "2023-11-05",
    totalHours: 389,
    averageRating: 4.8,
    lastActive: "2024-12-15 16:45",
  },
  {
    id: "student-004",
    name: "Taylor Swift",
    email: "taylor@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Taylor",
    enrolledCourses: 2,
    completionRate: 45,
    status: "Suspended",
    joinDate: "2024-03-20",
    totalHours: 67,
    averageRating: 3.2,
    lastActive: "2024-12-10 09:15",
  },
  {
    id: "student-005",
    name: "Morgan Parker",
    email: "morgan@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Morgan",
    enrolledCourses: 4,
    completionRate: 78,
    status: "Active",
    joinDate: "2024-04-12",
    totalHours: 203,
    averageRating: 4.4,
    lastActive: "2024-12-15 13:50",
  },
]

export const mockInstructors: Instructor[] = [
  {
    id: "inst-001",
    name: "John Smith",
    email: "john@eduhub.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
    assignedCourses: 3,
    totalStudents: 4500,
    revenue: 125000,
    rating: 4.8,
    status: "Approved",
    joinDate: "2023-06-10",
    bio: "Expert React developer with 10+ years of experience",
  },
  {
    id: "inst-002",
    name: "Emily Johnson",
    email: "emily@eduhub.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily",
    assignedCourses: 2,
    totalStudents: 3200,
    revenue: 98000,
    rating: 4.7,
    status: "Approved",
    joinDate: "2023-08-15",
    bio: "Data scientist and machine learning specialist",
  },
  {
    id: "inst-003",
    name: "Michael Chen",
    email: "michael@eduhub.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
    assignedCourses: 2,
    totalStudents: 2800,
    revenue: 85000,
    rating: 4.6,
    status: "Approved",
    joinDate: "2023-09-20",
    bio: "Business strategist and management consultant",
  },
  {
    id: "inst-004",
    name: "New Designer",
    email: "designer@eduhub.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Designer",
    assignedCourses: 0,
    totalStudents: 0,
    revenue: 0,
    rating: 0,
    status: "Pending",
    joinDate: "2024-12-01",
    bio: "UI/UX designer seeking approval",
  },
]

export const mockAnalytics: AnalyticsData[] = [
  { date: "Jan 1", students: 1200, revenue: 45000, completions: 320 },
  { date: "Jan 8", students: 1350, revenue: 52000, completions: 380 },
  { date: "Jan 15", students: 1520, revenue: 58000, completions: 450 },
  { date: "Jan 22", students: 1680, revenue: 62000, completions: 520 },
  { date: "Jan 29", students: 1850, revenue: 71000, completions: 610 },
  { date: "Feb 5", students: 2100, revenue: 80000, completions: 720 },
  { date: "Feb 12", students: 2340, revenue: 89000, completions: 850 },
]

export const mockTransactions: Transaction[] = [
  {
    id: "txn-001",
    studentId: "student-001",
    courseId: "course-001",
    amount: 99.99,
    date: "2024-12-15",
    status: "Completed",
    paymentMethod: "Credit Card",
  },
  {
    id: "txn-002",
    studentId: "student-002",
    courseId: "course-002",
    amount: 129.99,
    date: "2024-12-14",
    status: "Completed",
    paymentMethod: "PayPal",
  },
  {
    id: "txn-003",
    studentId: "student-003",
    courseId: "course-004",
    amount: 109.99,
    date: "2024-12-14",
    status: "Completed",
    paymentMethod: "Credit Card",
  },
]

export const mockLessons: Lesson[] = [
  {
    id: "lesson-001",
    courseId: "course-001",
    title: "Introduction to Hooks",
    module: 1,
    order: 1,
    duration: 45,
    type: "video",
    status: "Published",
  },
  {
    id: "lesson-002",
    courseId: "course-001",
    title: "Context API Deep Dive",
    module: 1,
    order: 2,
    duration: 60,
    type: "video",
    status: "Published",
  },
  {
    id: "lesson-003",
    courseId: "course-001",
    title: "Custom Hooks Practice",
    module: 2,
    order: 1,
    duration: 90,
    type: "assignment",
    status: "Published",
  },
]
